coverage:
  precision: 2
  round: down
  range: 88...100

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project:
      default:
        enabled: yes
        target: auto
        threshold: 0.1
    patch:
      default:
        enabled: yes
        target: auto
        threshold: 0.1
